#version: '3.8'  #Depuis Docker Compose v2.20+, l’attribut version: en haut du fichier docker-compose.yml est obsolète

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.9.1-python3.11
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
      - ./.env:/opt/airflow/.env
      - ./config/trustpilot-satisfaction-43aac3dd82a9.json:/opt/airflow/project/config/trustpilot-satisfaction-43aac3dd82a9.json
    ports:
      - "8080:8080"
    entrypoint: bash -c "pip install --no-cache-dir -r /requirements.txt && /opt/airflow/entrypoint.sh"
    env_file:
      - .env
    command: webserver

  scheduler:
    image: apache/airflow:2.9.1-python3.11
    depends_on:
      - webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow/project
    entrypoint: /opt/airflow/entrypoint.sh
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
      - ./.env:/opt/airflow/.env
      - ./config/trustpilot-satisfaction-43aac3dd82a9.json:/opt/airflow/project/config/trustpilot-satisfaction-43aac3dd82a9.json
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default
    depends_on:
      - webserver

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - default

  exporter:
    build:
      context: ./monitoring
    ports:
      - "8000:8000"
    networks:
      - default
  
volumes:
  postgres-db-volume:
