FROM apache/airflow:2.9.1-python3.11

# Copie le fichier requirements.txt dans le conteneur
COPY requirements.txt /requirements.txt

# Installation des dépendances
RUN pip install --no-cache-dir -r /requirements.txt

# Ajout optionnel : définition du répertoire de travail
WORKDIR /opt/airflow
