name: CI - Feedbacks analysis

on: 
  push:
    branches:
      - main
      - airflow-grafana-prometheus
      - ci-gcp-integration
  pull_request:
    branches:
      - main
      - airflow-grafana-prometheus
      - ci-gcp-integration
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt 
      
      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > gcp-creds.json
        shell: bash

      - name: Run tests and generate report
        run: |
          PYTHONPATH=$(pwd) pytest --junitxml=tests/reports/results.xml tests/ --disable-warnings --maxfail=1 --ignore=tests/test_dag_workflow.py

      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/reports/
    
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      DATASET_ID: ${{ secrets.DATASET_ID }}
      TABLE_ID: ${{ secrets.TABLE_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
